import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pages and Layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="text-white justify-center text-center gap-12 flex mt-12 ">
          <Link
            className="hover:bg-white hover:text-black p-3 rounded-lg"
            href="/"
          >
            Home
          </Link>
          <Link
            className="hover:bg-white hover:text-black p-3 rounded-lg"
            href="/about"
          >
            About
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
