import React from "react";
import getAllUser from "../lib/getAllUser";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Users Page",
  description: "Generated by create next app",
};

export default async function UsersPage() {
  const userData: Promise<User[]> = getAllUser();

  const users = await userData;

  const content = (
    <section>
      <h2>Users Page</h2>
      <Link href="/">Go to the Home Page</Link>
      <h1>Users</h1>
      {users.map((user) => (
        <div key={user.id}>
          <p>
            <Link href={`/users/${user.id}`}>{user.name}</Link>
          </p>
        </div>
      ))}
    </section>
  );
  return content;
}
